### ISSUE TITLE
Generate JWT for Apple Push Notification

### ISSUE THREAD

**Issue by edamov** [namshi/jose#108]
I want to use `jose` library for generating JWT for Apple Push Notification.
But I don't know how to implement it with this library.
There are some [requirements](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html) for generating this token:
1) Headers should be:

``` json
{
    "alg": "ES256",
    "kid": "ABC123DEFG"
}
```

2) Payload data should be:

``` json
{
    "iss": "DEF123GHIJ",
    "iat": 1437179036
 }
```

3) APNs supports only provider authentication tokens that are signed with the ES256 algorithm.

So could you please provide an example of generating JWT token for Apple Push Notifications with you library?

**Comment by YaniceSC** [comment]
Hi @edamov,
did you find a solution ?
thanks.

**Comment by edamov** [comment]
@YaniceSC Yes, I did. I found another library [Spomky-Labs/jose](https://github.com/Spomky-Labs/jose).
[Here](https://gist.github.com/edamov/0f3ba7ef4eb9b3df4372ff2058a168a4) you can find an example.
Also I've started to develop the library for sending push notifications - [edamov/pushok](https://github.com/edamov/pushok)

**Comment by YaniceSC** [comment]
Great! I will have look then.
thanks.
