### ISSUE TITLE
JSON Encryption vulnerability question

### ISSUE THREAD

**Issue by AndresPuig** [namshi/jose#117]
Does this vulnerability affects this library?
http://blogs.adobe.com/security/2017/03/critical-vulnerability-uncovered-in-json-encryption.html

Thanks in advance!

**Comment by Spomky** [comment]
This vulnerability only concerns ECDH-ES encryption algorithms (not supported by this library).

**Comment by odino** [comment]
Thanks @Spomky :)

**Comment by AndresPuig** [comment]
Thanks!
