### ISSUE TITLE
No encryption support

### ISSUE THREAD

**Issue by greg0ire** [namshi/jose#22]
The 'e' of JOSE means "encryption", but I can't see how to transfer sensitive data with this library. I think I have to write my own `Encoder` implementation, and inject it in the `JWT` instance. Maybe there should be a § in the documentation about that, I can contribute it if you want.

**Comment by greg0ire** [comment]
Writing my own encoder works well for generating a token, but there is no way to override it so that it can be used in the static `load` method…

**Comment by odino** [comment]
hey @greg0ire, it would be great to have you contribute to this with a PR! Would you be able to try to hack on it? Im available if you need any help / explanation

cheers!

**Comment by greg0ire** [comment]
I could do that, yeah… I think an easy, backwards compatible solution to this problem would be to have a new argument added to the static `load` method. This argument should default to null to maintain BC. If you're fine with that I can contribute it when I have the time.

**Comment by odino** [comment]
BTW Id say have a look at the JWS spec or what others drivers do :) http://jwt.io/

**Comment by greg0ire** [comment]
Nice website, but I'm not sure what you want me to do with this… If I understand correctly, encryption is not part of the JWS at all, but of [JWE](http://self-issued.info/docs/draft-ietf-jose-json-web-encryption.html).

**Comment by odino** [comment]
what I mean is that probably these guys have some sort of encryption in one
of the libraries, so you could have a look and take inspiration from them :)

On Tue, Feb 10, 2015 at 5:17 PM, Grégoire Paris <notifications@github.com>
wrote:

> Nice website, but I'm not sure what you want me to do with this… If I
> understand correctly, encryption is not part of the JWS at all, but of JWE
> <http://self-issued.info/docs/draft-ietf-jose-json-web-encryption.html>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/namshi/jose/issues/22#issuecomment-73697225>.
>



-- 
Nadalin Alessandro
http://www.linkedin.com/in/alessandronadalin
www.odino.org
www.twitter.com/_odino_

**Comment by greg0ire** [comment]
Oh ok… thanks!

**Comment by Spomky** [comment]
@greg0ire this library does not support encryption. That is why I sent you an email to test my own implementation.
After our email exchanges, I created a new sub-project that ease the use of my library. See [Spomky-Labs/jose-service](https://github.com/Spomky-Labs/jose-service) (WIP, documentation has to be written).

Feedbacks are welcomed.

**Comment by greg0ire** [comment]
I know it does not, but I'm suggesting letting people override the encoder if they want to, so that they can easily create JWEs and still use the logic of the library. ATM, I'm not using namshi/jose due to this limitation but a simpler implementation that does not  comply with the JWT standard because it does not have any signing, only encryption.

Anyway, when your pimple-based lib is ready to use, people should probably have an easier time using it.
