### ISSUE TITLE
Should `composer.lock` be committed?

### ISSUE THREAD

**Issue by brianjmiller** [namshi/jose#25]
For a library it was my understanding that typically the `composer.lock` shouldn't be in the repo. See:

http://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control

Make sure to have a look at the 2nd and 3rd answers not just the accepted one. I didn't want to be so bold as to change the meta files of a project I don't own, but noticed it in my repo so thought I'd mention it. I'm happy to PR if necessary.

**Comment by odino** [comment]
I think we can keep it as it doesnt really create harm :) Quoting [one answer](http://stackoverflow.com/a/24247443/934439):

> For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions

So I guess we're ok to keep it since it doesnt harm anyone :-P
