### ISSUE TITLE
strlen() and substr() can misbehave with mbstring.func_overload

### ISSUE THREAD

**Issue by sarciszewski** [namshi/jose#34]
https://github.com/namshi/jose/blob/a418f6ca541865a6a96b4645c23cf973bf215f86/src/Namshi/JOSE/Signer/OpenSSL/HMAC.php#L50-L51

See also:

https://github.com/ircmaxell/SecurityLib/blob/master/lib/SecurityLib/Util.php#L32-L66

**Comment by cirpo** [comment]
@sarciszewski thanks, will look into it
