### ISSUE TITLE
Tag 6.0.2 has a dependency on phpseclib ~2.0 which is backwards incompatible

### ISSUE THREAD

**Issue by bendbennett** [namshi/jose#55]
Currently, installing namshi/jose using composer pulls in the 6.0.2 tag
`"namshi/jose": "6.0.*"`

The 6.0.2 tag has a dependency on phpseclib ~2.0 
`"phpseclib/phpseclib": "~2.0"`

Owing to changes in phpseclib, this breaks the *supportsKey()* method in the ECDSA class
`Fatal error: Class 'File_ASN1' not found in ECDSA.php on line 40`

Class has been renamed in phpseclib ~2.0 to ASN1 (/phpseclib/File/ASN1.php)
Fix is to update the use statement in ECDSA.php from `use \File_ASN1;` to `use phpseclib\File\ASN1;`
and to update the names of the constants used in the ECDSA class with the constants defined in the ASN1 class.

The master branch currently has a dependency on phpseclib 1.0.0 `"phpseclib/phpseclib": "1.0.0"` and looking at the git log it seems that tag 6.0.2 was created from commit `fd465401723974d76beb7424aeb4964c26b2b435` before the switch to phpseclib 1.0.0 was committed. I'm happy to submit a pull request if you're going to change to phpseclib ~2.0. If you're going to stick with 1.0.0 could you create tag 6.0.3 from master. Thanks!

**Comment by jyggen** [comment]
Having this issue as well, a new release with the 1.0 rollback would be appreciated. Thanks!

**Comment by bendbennett** [comment]
@jyggen for now I've just gone the route of editing my composer.json file as follows:
`"namshi/jose": "6.0.1*"`

**Comment by cirpo** [comment]
@jyggen @bendbennett a new version has been released.
I rolled back to phpseclib 1.0. Tag 6.0.3 also contains support for PHP7, unfortunately if you use ECDSA it will not work. I'm more than happy if we could move to phpseclib 2 and have full PHP7 support, but it seems not the case atm for phpseclib, plus it seems that version 1.0 is the LTS : https://github.com/phpseclib/phpseclib/issues/842 :(

**Comment by cirpo** [comment]
@jyggen @bendbennett let me know if you have any issue with the new tag, thanks

**Comment by jyggen** [comment]
Seems to work fine here :+1:

**Comment by bendbennett** [comment]
@jyggen - many thanks, all good at this end

**Comment by cirpo** [comment]
closing this issue

**Comment by cirpo** [comment]
@bendbennett @jyggen could you please try this branch https://github.com/namshi/jose/commits/phpseclib-2 ? Tests are passing and everything seems fine, but I want double check with you. Thanks, really appreciated /cc

**Comment by paceto256** [comment]
Fatal error: Class 'phpseclib\File\ASN1' not found in /home/paceto/proj/sgapi/vendor/namshi/jose/src/Namshi/JOSE/Signer/OpenSSL/ECDSA.php on line 46
