### ISSUE TITLE
will `json_encode` preserve the order of keys in the header/payload array?

### ISSUE THREAD

**Issue by ekousp** [namshi/jose#87]
The [generateSigninInput](https://github.com/namshi/jose/blob/master/src%2FNamshi%2FJOSE%2FJWT.php#L58) use `json_encode` to get signinInput.

will `json_encode` preserve the order of keys in the header/payload array? will it always generate **the same** output with original encoded header/payload?

**Comment by odino** [comment]
hey @ekousp, you should check this on the PHP doc itself: http://php.net/manual/en/function.json-encode.php#107616

Cheers!
